### ISSUE TITLE
Can't ssh to the watch (Broken pipe)

### ISSUE THREAD

**Issue by dalz** [AsteroidOS/meta-mtk6580-hybris#8]
Since I flashed the nightly build I downloaded on February 14 I can't ssh to my KW88 Pro through USB anymore. Below is the output I get:

```
$ ssh ceres@192.168.2.15
client_loop: send disconnect: Broken pipe
```

Same happens with `root`.
If I roll back to the image I had before (downloaded on January 24) it works as it should.

Can someone please take a look at this?

**Comment by MagneFire** [comment]
Hi dalz, this issue isn't actually unique to mtk6580 devices. It seems that sturgeon also suffers from this problem.
I have worked out that this has something to do with an update to the OpenSSL libraries. I will prepare a PR for this in a moment. That should hopefully fix this problem in the next nightly.

**Comment by dalz** [comment]
Thank you for the quick response!
